// Taken from my previous project, namely BOOT:NT
// However, this was generated by AI in the previous project

"use client";

import { useEffect, useRef } from "react";

export default function AnimatedBackground() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let animationFrameId: number;
    let width = window.innerWidth;
    let height = window.innerHeight;

    // Track mouse position
    let mouse = { x: width / 2, y: height / 2 };
    // Track smoothed mouse for inertia
    let smoothMouse = { x: width / 2, y: height / 2 };

    const handleMouseMove = (e: MouseEvent) => {
      mouse.x = e.clientX;
      mouse.y = e.clientY;
    };

    window.addEventListener("mousemove", handleMouseMove);

    const resize = () => {
      width = window.innerWidth;
      height = window.innerHeight;
      canvas.width = width;
      canvas.height = height;
    };

    window.addEventListener("resize", resize);
    resize();

    const spacing = 40; // Spacing between dots

    const draw = (time: number) => {
      // Lerp smooth mouse for inertia effect
      smoothMouse.x += (mouse.x - smoothMouse.x) * 0.05;
      smoothMouse.y += (mouse.y - smoothMouse.y) * 0.05;

      // Calculate parallax offset (relative to center)
      const parallaxX = (smoothMouse.x - width / 2) * 0.1;
      const parallaxY = (smoothMouse.y - height / 2) * 0.1;

      ctx.clearRect(0, 0, width, height);
      ctx.fillStyle = "rgba(254, 234, 250, 0.2)"; // Secondary color faintly translucent

      // Expand loop bounds slightly to ensure edges don't pop during parallax
      const cols = Math.ceil(width / spacing) + 4;
      const rows = Math.ceil(height / spacing) + 4;

      for (let i = -2; i < cols; i++) {
        for (let j = -2; j < rows; j++) {
          const basePathX = i * spacing;
          const basePathY = j * spacing;

          // Organic orbit based on position and time using sin/cos
          const phase = i * 0.3 + j * 0.3;
          const orbitX = Math.cos(time * 0.0015 + phase) * 4;
          const orbitY = Math.sin(time * 0.0015 + phase) * 4;

          const x = basePathX + orbitX + parallaxX;
          const y = basePathY + orbitY + parallaxY;

          ctx.beginPath();
          ctx.arc(x, y, 1.5, 0, Math.PI * 2);
          ctx.fill();
        }
      }

      animationFrameId = requestAnimationFrame(draw);
    };

    draw(0);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("resize", resize);
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="absolute inset-0 w-full h-full pointer-events-none"
    />
  );
}